import { useCallback } from 'react';
import jsPDF from 'jspdf';
import type { SessionStats, SkillEstimate } from './useSimulator';

interface CurrentHole {
  id: number;
  distance: number;
  targetRadius: number;
  k: number;
}

interface ExportData {
  handicap: number;
  sessionStats: SessionStats;
  skillEstimate: SkillEstimate;
  currentHole: CurrentHole;
  breakevenRadius: number;
}

export const useExportPDF = () => {
  const exportToPDF = useCallback((data: ExportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(73, 59, 124); // Golf purple
    doc.text('Continuum Golf Session Report', pageWidth / 2, 20, { align: 'center' });

    // Subtitle
    doc.setFontSize(12);
    doc.setTextColor(158, 140, 180);
    doc.text(new Date().toLocaleDateString(), pageWidth / 2, 28, { align: 'center' });

    // Section 1: Player Profile
    let yPos = 45;
    doc.setFontSize(16);
    doc.setTextColor(96, 76, 156);
    doc.text('Player Profile', margin, yPos);

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    yPos += 10;
    doc.text(`Handicap: ${data.handicap}`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Skill Estimate (σ): ${data.skillEstimate.sigma.toFixed(2)} yards`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Confidence: ${data.skillEstimate.confidence.toFixed(1)}%`, margin + 5, yPos);
    yPos += 7;
    doc.text(`P_max: ${data.skillEstimate.pmax.toFixed(3)}`, margin + 5, yPos);

    // Section 2: Session Statistics
    yPos += 15;
    doc.setFontSize(16);
    doc.setTextColor(96, 76, 156);
    doc.text('Session Statistics', margin, yPos);

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    yPos += 10;
    doc.text(`Total Shots: ${data.sessionStats.shotsTaken}`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Total Wagered: $${data.sessionStats.totalWagered.toFixed(2)}`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Total Won: $${data.sessionStats.totalWon.toFixed(2)}`, margin + 5, yPos);
    yPos += 7;

    // Net P/L with color
    const isProfit = data.sessionStats.netPL >= 0;
    doc.setTextColor(isProfit ? 34 : 239, isProfit ? 197 : 68, isProfit ? 94 : 68);
    doc.text(`Net P/L: ${isProfit ? '+' : ''}$${data.sessionStats.netPL.toFixed(2)}`, margin + 5, yPos);

    doc.setTextColor(50, 50, 50);
    yPos += 7;
    doc.text(`House Edge: ${data.sessionStats.actualHouseEdge.toFixed(1)}%`, margin + 5, yPos);

    // Section 3: Hole Configuration
    yPos += 15;
    doc.setFontSize(16);
    doc.setTextColor(96, 76, 156);
    doc.text('Hole Configuration', margin, yPos);

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    yPos += 10;
    doc.text(`Hole #${data.currentHole.id} (${data.currentHole.distance} yards)`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Target Radius: ${data.currentHole.targetRadius.toFixed(2)} yards`, margin + 5, yPos);
    yPos += 7;
    doc.text(`Breakeven Radius: ${data.breakevenRadius.toFixed(2)} yards`, margin + 5, yPos);

    // Section 4: System Information
    yPos += 15;
    doc.setFontSize(16);
    doc.setTextColor(96, 76, 156);
    doc.text('System Information', margin, yPos);

    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    yPos += 10;
    doc.text('Algorithm: Kalman Filter with Bivariate Normal Distribution', margin + 5, yPos);
    yPos += 7;
    doc.text('Target RTP: 85% (House Edge: 15%)', margin + 5, yPos);
    yPos += 7;
    doc.text('Fairness: Equal expected value across all skill levels', margin + 5, yPos);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(158, 140, 180);
    const footer = 'Generated by Continuum Golf Simulator - Rust + WebAssembly';
    doc.text(footer, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

    // Download
    const filename = `continuum-session-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
  }, []);

  return { exportToPDF };
};
